{% set name = "GPopt" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Techtonique/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 3d835410ef88b9111c2c995ed56233249dd8be8ccaab554f3f3b93f5c94a58c0

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py < 35]
  skip: true  # [win]

requirements:
  host:
    - python
    - pip
    - setuptools
    - matplotlib-base
    - numpy >=1.14.0
    - scipy >=0.19.0
    - Click 
    - joblib
    - nnetsauce 
    - numpy
    - pandas
    - scipy
    - scikit-learn
    - threadpoolctl
    - tqdm
  run:
    - python
    - scipy >=0.19.0
    - matplotlib-base
    - Click 
    - joblib
    - nnetsauce 
    - numpy
    - pandas
    - scipy
    - scikit-learn
    - threadpoolctl
    - tqdm
    - {{ pin_compatible('numpy') }}

test:
  imports: GPopt

about:
  home: https://techtonique.github.io/GPopt/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Stochastic optimization using Machine Learning surrogates
  description: Stochastic optimization using Machine Learning surrogates
  doc_url: https://techtonique.github.io/GPopt/
  dev_url: https://github.com/Techtonique/GPopt

extra:
  recipe-maintainers:
    - thierrymoudiki
