# Note: there are many handy hints in comments in this example -- remove them when you've finalized your recipe

{% set name = "nnetsauce" %}
{% set version = "0.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

package:
  name: nnetsauce
  version: 0.8.3

source:
  url: https://github.com/Techtonique/nnetsauce/tree/master/dist/nnetsauce-0.8.3.tar.gz  # [not win]
  url: https://github.com/Techtonique/nnetsauce/tree/master/dist/nnetsauce-0.8.3.zip  # [win]  

build:
  number: 0  
  skip: True  # [py<35]

requirements:
  build:
    - python
    - setuptools
    - cython  
  run:
    - python

about:
  home: https://github.com/Techtonique/nnetsauce  
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    # Always check with the people listed below if they are OK becoming maintainers of the recipe. (There will be spam!)
    - thierrymoudiki    
