# Note: there are many handy hints in comments in this example -- remove them when you've finalized your recipe

{% set name = "nnetsauce" %}
{% set version = "0.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

package:
  name: nnetsauce
  version: 0.8.3

source:
  url: https://pypi.io/packages/source/{{name[0]}}/{{ name }}/{{ name }}-{{ version }}.tar.gz  
  sha256: d58439c548433adcda98e695be53e526ba940a4b9c44fb9a05d92cd495cdd47f

build:
  number: 0
  skip: true  # [win]
  skip: True  # [py<35]

requirements:
  build:
    - python
    - setuptools
    - cython  
  run:
    - python

about:
  home: https://github.com/Techtonique/nnetsauce  
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    # Always check with the people listed below if they are OK becoming maintainers of the recipe. (There will be spam!)
    - thierrymoudiki    
